export default [
    { "text": "Albama", "value": "CT" },
    { "text": "Alaska", "value": "Pt" },
    { "text": "Arizona", "value": "Mt" },
    { "text": "Arkansas", "value": "Et" },
    { "text": "California", "value": "At" },
    { "text": "Colorado", "value": "Ha" },
    { "text": "Connecticut", "value": "CT" },
    { "text": "Delware", "value": "Pt" },
    { "text": "Florida", "value": "Mt" },
    { "text": "Georgia", "value": "Et" },
    { "text": "Hawaii", "value": "At" },
    { "text": "Idaho", "value": "Ha" },
    { "text": "Illinois", "value": "CT" },
    { "text": "Indiana", "value": "Pt" },
    { "text": "Iowa", "value": "Mt" },
    { "text": "Kansas", "value": "Et" },
    { "text": "Kentucky", "value": "At" },
    { "text": "Louisiana", "value": "Ha" },
    { "text": "Maine", "value": "CT" },
    { "text": "Maryland", "value": "Pt" },
    { "text": "Massachusetts", "value": "Mt" },
    { "text": "Michigan", "value": "Et" },
    { "text": "Minnesota", "value": "At" },
    { "text": "Mississipi", "value": "Ha" },
    { "text": "Missouri", "value": "CT" },
    { "text": "Montana", "value": "Pt" },
    { "text": "Nebraska", "value": "Mt" },
    { "text": "Nevada", "value": "Et" },
    { "text": "New Hampshire", "value": "At" },
    { "text": "New Jersey", "value": "Ha" },
    { "text": "New Mexico", "value": "CT" },
    { "text": "New York", "value": "Pt" },
    { "text": "North Carolina", "value": "Mt" },
    { "text": "North Dakota", "value": "Et" },
    { "text": "Ohio", "value": "At" },
    { "text": "Oklahoma", "value": "Ha" },
    { "text": "Oregon", "value": "Pt" },
    { "text": "Pennsylvania", "value": "Mt" },
    { "text": "Rhode Island", "value": "Et" },
    { "text": "South Carolina", "value": "At" },
    { "text": "South Dakota", "value": "Ha" },
    { "text": "Tennessee", "value": "CT" },
    { "text": "Texas", "value": "Pt" },
    { "text": "Utah", "value": "Mt" },
    { "text": "Vermont", "value": "Et" },
    { "text": "Virginia", "value": "At" },
    { "text": "Washington", "value": "Ha" },
    { "text": "West Virginia", "value": "Pt" },
    { "text": "Wisconsin", "value": "Mt" },
    { "text": "Wyoming", "value": "Et" },
    { "text": "Puerto Rico", "value": "At" },
   
]